Updates

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -32,10 +32,13 @@ jobs:
       - name: Run Tests with Coverage
         run: |
           dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory:TestResults
-          dotnet tool run dotnet-coverage -- check-coverage --threshold 100
+          if [ $? -ne 0 ]; then
+            echo "Tests failed or coverage threshold not met"
+            exit 1
+          fi
 
       - name: Upload Coverage Report
         uses: actions/upload-artifact@v4
         with:
           name: Code-Coverage-Report
-          path: ${{ github.workspace }}/TestResults/*/coverage.cobertura.xml
+          path: ${{ github.workspace }}/DbLocatorTests/CoverageReport
